- hosts: ec2
  become: yes
  tasks:
  # any task name
  - name: important packages
    apt:
      pkg:
        - curl
        - vim
        - git
        - ufw
        - npm
      state: latest
      update_cache: true

  - name: Add NodeSource repository for Node.js 18.x
    apt:
      deb: https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.19.1-deb-1nodesource1_amd64.deb
    ignore_errors: yes

  - name: Install Node.js and npm
    apt:
      name: nodejs
      state: latest
      update_cache: true

  - name: Ensure npm is latest
    npm:
      name: npm
      global: yes
      state: latest

  - name: Install pm2 globally via npm
    npm:
      name: pm2
      global: yes

