###

Get http://localhost:3000/log

###
POST http://localhost:3000/postData

Content-Type: application/json

{
    "name": "Tes",
    "email": "abcmail.com"
}

###

GET  http://localhost:3000/setup
{
    "name": "logtest",
    "status": "created"
}